import { db } from "@/lib/backup-db/index";
import { products } from "@/lib/backup-db/products";

export async function seedProducts() {
  const items = [
    {
      stripeProductId: "prod_UthgX9QWKCUMpa",
      stripePriceId: "price_1TtuHFDFcm24Wdf0wJwriW9p",
      name: "26Scan (All Products Included)",
      description: "",
      interval: "year",
      amount: 53881,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthdAnuV6vo3re",
      stripePriceId: "price_1TtuE6DFcm24Wdf02misZJ4B",
      name: "26Scan (All Modules Included)",
      description: "",
      interval: "month",
      amount: 4989,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Uthamn7KYgxcyK",
      stripePriceId: "price_1TtuBiDFcm24Wdf0yko9CzTC",
      name: "Reports",
      description: "",
      interval: "year",
      amount: 2149,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthZNBYr07Bcgx",
      stripePriceId: "price_1TtuAZDFcm24Wdf0Smxn2sYp",
      name: "Reports",
      description: "",
      interval: "month",
      amount: 199,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthYRIsusEN47X",
      stripePriceId: "price_1Ttu9GDFcm24Wdf0rqrokzss",
      name: "Heatmap",
      description: "",
      interval: "year",
      amount: 2149,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthWp9RTedvcBW",
      stripePriceId: "price_1Ttu7eDFcm24Wdf03IhF7XkP",
      name: "Heatmap",
      description: "",
      interval: "month",
      amount: 199,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthVgsoWyZuKsa",
      stripePriceId: "price_1Ttu6mDFcm24Wdf0i4hRqk1O",
      name: "Website Scanner",
      description: "",
      interval: "year",
      amount: 2149,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthTL0av2TzgS6",
      stripePriceId: "price_1Ttu4yDFcm24Wdf0eQB0HRn5",
      name: "Website Scanner",
      description: "",
      interval: "month",
      amount: 199,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthRD4HIWIgc8h",
      stripePriceId: "price_1Ttu31DFcm24Wdf07Aj04Hwk",
      name: "Predictive Analysis",
      description: "",
      interval: "year",
      amount: 7549,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthPPFpKbQfNJ5",
      stripePriceId: "price_1Ttu0kDFcm24Wdf0GLtQc6Cb",
      name: "Predictive Analysis",
      description: "",
      interval: "month",
      amount: 699,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthLRKJb2cet4Q",
      stripePriceId: "price_1Tttx7DFcm24Wdf0OiFO19Ty",
      name: "FARGUS Engine",
      description: "",
      interval: "year",
      amount: 8629,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UthIH7VxF4HKtj",
      stripePriceId: "price_1TtttbDFcm24Wdf0U27SnYgB",
      name: "FARGUS Engine",
      description: "",
      interval: "month",
      amount: 799,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Uth8rEp82BCfSs",
      stripePriceId: "price_1TttkhDFcm24Wdf05uJYOnEk",
      name: "Compliance",
      description: "",
      interval: "year",
      amount: 4309,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Uth7t3ykyJgejh",
      stripePriceId: "price_1TttjbDFcm24Wdf0VlGWk3as",
      name: "Compliance",
      description: "",
      interval: "month",
      amount: 399,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Uth76yFuzpB6QL",
      stripePriceId: "price_1TttiqDFcm24Wdf0hHbwkXdV",
      name: "Trend",
      description: "",
      interval: "year",
      amount: 4309,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Uth6QvzqJ5dRC0",
      stripePriceId: "price_1TtthsDFcm24Wdf0krPIf8i1",
      name: "Trend",
      description: "",
      interval: "month",
      amount: 399,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Uth5jcAgiU3CeA",
      stripePriceId: "price_1TttgvDFcm24Wdf0JajCqskY",
      name: "Alerts",
      description: "",
      interval: "year",
      amount: 4309,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Uth3foRxEOkkdd",
      stripePriceId: "price_1Tttf7DFcm24Wdf0k5GtLImA",
      name: "Alerts",
      description: "",
      interval: "month",
      amount: 399,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Utgx766yZnN2uX",
      stripePriceId: "price_1TttZkDFcm24Wdf0QEsGHpqY",
      name: "PII Leakage Detection",
      description: "",
      interval: "year",
      amount: 4309,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UtgwNQl0lwwMxa",
      stripePriceId: "price_1TttYADFcm24Wdf05dtS6BC7",
      name: "PII Leakage Detection",
      description: "",
      interval: "month",
      amount: 399,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UtguFCfSZHmB9W",
      stripePriceId: "price_1TttWpDFcm24Wdf0y9tDSUnb",
      name: "GEO Analytics",
      description: "",
      interval: "year",
      amount: 4309,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UtgHnPcaBzkLT2",
      stripePriceId: "price_1TtsupDFcm24Wdf03T9rwdQ3",
      name: "GEO Analytics",
      description: "",
      interval: "month",
      amount: 399,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UtgFOmEE4RZfxj",
      stripePriceId: "price_1TtstJDFcm24Wdf0786ezZ59",
      name: "SEO Evaluation",
      description: "",
      interval: "year",
      amount: 4309,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UtgDzLeYNQ1czN",
      stripePriceId: "price_1Ttsr8DFcm24Wdf0SojZGdz6",
      name: "SEO Evaluation",
      description: "",
      interval: "month",
      amount: 399,
      currency: "usd",
    },
    {
      stripeProductId: "prod_UtgB0c2Sd21Dks",
      stripePriceId: "price_1TtsonDFcm24Wdf0nrT2sPO7",
      name: "Security Evaluation",
      description: "",
      interval: "year",
      amount: 5389,
      currency: "usd",
    },
    {
      stripeProductId: "prod_Utg7f9pt1wiDvs",
      stripePriceId: "price_1TtslMDFcm24Wdf0P8YGf2Ex",
      name: "Security Evaluation",
      description: "",
      interval: "month",
      amount: 499,
      currency: "usd",
    },
  ];

  await db.insert(products).values(items);
}

